#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'


#a

cookbook "apache2"
cookbook "apt"

#b

cookbook "build-essential", "1.4.0"

#c

cookbook 'chef-client'
cookbook "cron"
cookbook 'chef-solo-search',
  :git => 'https://github.com/edelight/chef-solo-search',
  :ref => 'master'
cookbook "composer", "0.0.5"
#d

cookbook 'drush',
  :git => 'https://github.com/vasilykraev/chef-drush.git',
  :ref => 'master'

#e

#f

cookbook "firewall",
  :git => 'https://github.com/computerlyrik/chef-firewall.git',
  :ref => 'master'

#g

cookbook "git", "2.7.0"

#h

cookbook "htop"

#i

cookbook "iotop",
  :git => 'https://github.com/korishev/iotop.git',
  :ref => 'master'

#j

cookbook "java"
cookbook "jenkins", "1.2.0"

#k

#l

#m

cookbook "mysql"
cookbook "memcached"

#n

cookbook "nano"
cookbook "nginx"

#o

cookbook "openssl"
cookbook "openssh"

#p

cookbook 'platform_packages',
  :git => 'git://github.com/fnichol/chef-platform_packages.git',
  :ref => 'master'

cookbook 'postgis2',
  :git => 'git://github.com/vasilykraev/cookbook-postgis.git',
  :ref => 'master'
cookbook "postgresql"
cookbook "postfix", "3.0.0"

cookbook "phing",
  :git => 'https://github.com/goruha/chef-phing',
  :ref => 'add_shell_timeout_support'
cookbook "php",
  :git => 'https://github.com/ffuenf/chef-php.git',
  :ref => 'master'
cookbook 'phpmyadmin',
  :git => 'git://github.com/priestjim/chef-phpmyadmin.git',
  :ref => 'master'
cookbook 'phppgadmin',
  :git => 'git://github.com/arnebrasseur/chef-phppgadmin.git',
  :ref => 'master'
cookbook "phpunit"

cookbook "python"

#q

#r
#cookbook "rvm",
#  :git =>"https://github.com/fnichol/chef-rvm.git",
#  :ref => "master"

cookbook "rbenv", "1.5.0"

#s
cookbook "ssh_known_hosts"
cookbook "sphinx",
  :git => 'https://github.com/goruha/sphinx-cookbook.git',
  :ref => 'master'
cookbook "squid"
cookbook "subversion"

#t

#u

cookbook 'users'

#v

cookbook "varnish"
cookbook "vim", "1.0.2"

#w
cookbook 'windows', "1.10.0"
#x

#y

#cookbook "yumrepo", "2.0.0"


#z

cookbook 'zip',
  :git => 'https://github.com/phlipper/chef-zip.git',
  :ref => 'master'

cookbook "zsh"

cookbook 'dmg', "2.0.4"

#cookbook "yum", "2.3.2"




